steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--build-arg'
      - 'NEXT_PUBLIC_BACKEND_URL=$_NEXT_PUBLIC_BACKEND_URL'
      - '--build-arg'
      - 'NEXT_PUBLIC_GOOGLE_CLIENT_ID=$_NEXT_PUBLIC_GOOGLE_CLIENT_ID'
      - '-t'
      - 'gcr.io/upai-projects/nawabaifrontend'
      - '.'

images:
  - 'gcr.io/upai-projects/nawabaifrontend'
